#!/bin/bash

# This file is auto generated by this plugin: https://github.com/aallali/meta-header.nvim

# Fill in the following environment variables
export HDR_AUTHOR="Copyright © hi@allali.me"
export HDR_USERNAME="aallali"
export HDR_PROJECT="p2p"
export HDR_LICENSE="MIT"

echo "AUTHOR: $HDR_AUTHOR"
echo "USERNAME: $HDR_USERNAME"
echo "PROJECT: $HDR_PROJECT"
echo "LICENSE: $HDR_LICENSE"

# run "source hdr_meta.sh"
